<nav class="navbar">
    <div class="dropdown">
        <button class="dropbtn">Menu</button>
        <div class="dropdown-content">
            <a href="index.php">Início</a>
            <div class="sub-dropdown">
                <button class="sub-dropbtn">Clientes</button>
                <div class="sub-dropdown-content">
                    <a href="inserirCliente.PHP">Cadastrar Cliente</a>
                    <a href="listarCliente.PHP">Listar Todos</a>
                    <a href="BuscarCliente.PHP">Listar Clientes (ASC)</a>
                    <a href="PesquisarCliente.PHP">Pesquisar Cliente</a>
                    <a href="AtualizarCliente.PHP">Atualizar Cliente</a>
                    <a href="DeletarCliente.PHP">Excluir Cliente</a>
                </div>
            </div>
        </div>
    </div>
</nav>